language: python
python:
- '3.2'
- '3.3'
- '3.4'
install:
- pip install .
script: nosetests
before_deploy:
- git clone https://github.com/seiferma/travis-utils.git
deploy:
  provider: script
  script: travis-utils/python_deploy.sh
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = '3.3'
env:
  global:
  - DEPLOY_URL=https://pypi.python.org/pypi
  - DEPLOY_USER=seiferma
  - secure: "a0CKoG+k5Szzjrdd+DT5jZd0XM2EwS18/lcZ95duQuzWnxJBmma7l9gXZY8XvJmEJgkGwEBXG2Hmha7Yw+VVWShNIVf1Yv8hyDXrztB+aLDWCA+Giybef9m20tHBQvcLqJDiuU89wl/DG00+Iy+F3IBzv56DDVKGWUclwpapDgs="
